### ISSUE TITLE
Add listening profiles

### ISSUE THREAD

**Issue by rkowalsk** [psyKomicron/Croak#6]
Changing the settings every time you change activity (ie. from gaming to watching a movie) is annoying.  It would be great to have profiles you could pre-parameter and then switch between easily.

**Comment by psyKomicron** [comment]
Changing what settings : audio sessions levels, always on top... ?

**Comment by rkowalsk** [comment]
Sessions visible, their disposition their sound level and if they are muted.

**Comment by psyKomicron** [comment]
First implementation of this new design, go to :
 - Top left button > "Settings" (localized) > "Audio profiles".

Please tell me what you think. (installation same as usual, however untested)

[SND Vol (Package)_2.11.2.0_Test.zip](https://github.com/psyKomicron/SND-Vol/files/10033882/SND.Vol.Package._2.11.2.0_Test.zip)

**Comment by rkowalsk** [comment]
The update failed: `Le programme d'installation d'application n’a pas pu installer les dépendances du package. Demandez au développeur le package Microsoft.VCLibs.140.00.Debug.UWPDesktop.`

**Comment by psyKomicron** [comment]
I thought it might add the debug librairies automatically, i guess the installer does not.

Here's the release version of it : 
[SND Vol (Package)_2.11.4.0_Test.zip (release version)](https://github.com/psyKomicron/SND-Vol/files/10040731/SND.Vol.Package._2.11.4.0_Test.zip)

**Comment by rkowalsk** [comment]
It looks really good. Doesn't work tho, don't know if it was intended. Maybe a 'set as default' would be better than the checkbox, and it would be great to be able to switch between profiles easily.

**Comment by psyKomicron** [comment]
**Doesn't work tho, don't know if it was intended**
- Yes it does not work (only the UI is made right now).

**Maybe a 'set as default' would be better than the checkbox**
- "Set as default" sounds good. What do you mean by "better than the checkbox" ?

**Switch between profiles easily**
- Profiles will be easier to choose, what you see right now in the settings is only the profile editing. The solution that will be implemented is to have them in the top left button.
- Profiles could also be switched with hot keys, however it might lead to some keyboard saturation with the already complicated volume up/down hot keys.  If it does lead to keyboard saturation, i'll go for in-app shortcuts.

**Comment by rkowalsk** [comment]
I think it would be great to have a radio button or a "set as default" button on every profile, i don't see how you can choose your default profile with a single checkbox. If it is meant to set the profile as default at its creation, it means you can't change it without having to recreate a whole profile. Now i'm realising, is the little blue circle indicating which one is the default profile ? If yes does this mean the top profile is the default one ? Because it's not very explicit.

**Comment by rkowalsk** [comment]
It looks very good. The teaching tip is a good idea but the fact that you only get to see it once isn't very conveniant. I unintentionally closed the bubble before reading it and can't access it anymore, which might be a common issue. Also, having (i.e.) a `default` logo in place of the blue circle would be more explicit.

**Comment by psyKomicron** [comment]
![image](https://user-images.githubusercontent.com/49617466/203360484-4361a08a-b3c4-420b-9706-d624748a036d.png)
What's your opinion about this.

**Comment by rkowalsk** [comment]
Having both phrases is a bit duplicative (ça fait doublon). I agree the circle looks good but do you really need it if you have the left description ? Alternative to the circle : having a fixed slot at the top in which comes the top profile. Like a lighter background behind the top profile

**Comment by rkowalsk** [comment]
I find it weird to have a dot indicating which one is the default profile when it is determined by its position in the list. I would expect the dot to follow the profile when you move it around since it's like "written" on it.

**Comment by psyKomicron** [comment]
I just had a thought. Would it be good to save the window position with the window layout changing (from auto/horizontal/vertical) ? Same thing for the window position.
The window resizing and repositioning would be optional, to be toggled on from the audio profile edit page.

**Comment by psyKomicron** [comment]
# 2.11.10.0
## Changes
- Removed ability to set profiles as default
    - It made no sense to have a default profile when the last used profile is loaded on startup and when the switch between each profile is doable with 2 clicks (3 at most)
    - Removed red dot, and any other indications about default profiles.
- Added new UI to add existing audio sessions or to manually add one.
- Added button to disable hot keys.
- Increased settings window base size.
- Small changes to the notification pop-up to make it easier to read.

## Fixes
- Fixed not being able to set the volume to 100 or 0 (impacted audio profiles).
- Fixed various invisible deadlock bugs (memory leaks).

## Bugs
- Muting audio sessions no longer works. You can mute a session (by clicking on the volume icon under the session's slider) but then can no long
[Croak (Package)_2.11.10.0_x64.zip](https://github.com/psyKomicron/SND-Vol/files/10118233/Croak.Package._2.11.10.0_x64.zip)
er unmute it.
- App window can have an erratic behavior when resizing while it being snapped on the edge of a screen.

##

### Installer: [Croak (Package)_2.11.10.0_x64.zip](https://github.com/psyKomicron/SND-Vol/files/10118236/Croak.Package._2.11.10.0_x64.zip)
